# Generated by Django 3.2.4 on 2021-07-10 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('internalclassifieds', '0002_auto_20210710_1652'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listings',
            name='is_comments_enabled',
        ),
    ]
