# Generated by Django 3.2.4 on 2021-07-10 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internalclassifieds', '0003_remove_listings_is_comments_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='listings',
            name='is_comments_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
